name: money_gestor
description: "Gestor de Finanzas Personales Offline-First."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- IDIOMAS (Causa del conflicto anterior) ---
  flutter_localizations:
    sdk: flutter

  # --- State Management ---
  provider: ^6.1.1

  # --- Base de Datos Local (NoSQL) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Utilidades ---
  # ACTUALIZADO: Cambiamos a 0.20.2 para solucionar el error
  intl: ^0.20.2       
  
  uuid: ^4.3.3        # Para generar IDs únicos
  path_provider: ^2.1.2 

  # --- UI & UX ---
  fl_chart: ^0.66.0   # Gráficos
  google_fonts: ^6.1.0 
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

  # --- Generación de Código ---
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true