name: money_gestor
description: "Gestor de Finanzas Personales Offline-First."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- IDIOMAS ---
  flutter_localizations:
    sdk: flutter

  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

  # --- State Management ---
  provider: ^6.1.1

  # --- Base de Datos Local (NoSQL) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Utilidades ---
  intl: ^0.20.2 
  uuid: ^4.3.3
  path_provider: ^2.1.2 

  # --- UI & UX ---
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0 
  lucide_icons: ^0.257.0
  confetti: ^0.7.0 
  showcaseview: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

  # --- Generación de Código ---
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  # --- NUEVAS LIBRERÍAS PARA ICONO Y SPLASH (Faltaban estas) ---
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

# ==========================================
# CONFIGURACIÓN DEL ICONO DE LA APP
# ==========================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png" # ¡Asegúrate de haber guardado tu imagen aquí!
  min_sdk_android: 21

# ==========================================
# CONFIGURACIÓN DE PANTALLA DE CARGA (SPLASH)
# ==========================================
flutter_native_splash:
  color: "#1E293B" # Fondo Azul Oscuro (Tu tema)
  image: "assets/images/app_icon.png"
  android_12:
    image: "assets/images/app_icon.png"
    color: "#1E293B"
  ios: true
  android: true